# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-02-03 13:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20200203_1545'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='category',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='category',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
