# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-02-04 13:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_auto_20200204_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.Location'),
        ),
        migrations.AlterField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(to='news.Tags'),
        ),
    ]
